language: node_js

node_js:
  - '8'
  - '10'
  - '11'
  - '12'

script:
  - npm run lint
  - npm run test:cov
  - npm run build

after_success:
  - npx codecov

branches:
  only:
    - master

cache:
  yarn: true
